extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_area_proto_default__42860_lights;
extern Lights1 castle_grounds_dl_text_rainbow_lights;
extern u8 castle_grounds_dl_auto_ci8[];
extern u8 castle_grounds_dl_auto_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_death_plane_a_0_mesh_layer_1_vtx_0[64];
extern Gfx castle_grounds_dl_death_plane_a_0_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_start_plane_a_0_mesh_layer_1_vtx_0[38];
extern Gfx castle_grounds_dl_start_plane_a_0_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_001_mesh_layer_1_vtx_0[773];
extern Gfx castle_grounds_dl_Text_001_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_002_mesh_layer_1_vtx_0[990];
extern Gfx castle_grounds_dl_Text_002_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_003_mesh_layer_1_vtx_0[886];
extern Gfx castle_grounds_dl_Text_003_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_004_mesh_layer_1_vtx_0[961];
extern Gfx castle_grounds_dl_Text_004_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_005_mesh_layer_1_vtx_0[1068];
extern Gfx castle_grounds_dl_Text_005_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Text_006_mesh_layer_1_vtx_0[465];
extern Gfx castle_grounds_dl_Text_006_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_area_proto_default__42860[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_text_rainbow[];
extern Gfx mat_revert_castle_grounds_dl_text_rainbow[];
extern Gfx castle_grounds_dl_death_plane_a_0_mesh_layer_1[];
extern Gfx castle_grounds_dl_start_plane_a_0_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_003_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_004_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_005_mesh_layer_1[];
extern Gfx castle_grounds_dl_Text_006_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
