extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_evil_lair_floor_lights;
extern u8 sl_dl_cs_brokentile04_alb_ci8[];
extern u8 sl_dl_cs_brokentile04_alb_ci8_pal_rgba16[];
extern Vtx sl_dl_Plane_016_mesh_layer_5_vtx_0[37];
extern Gfx sl_dl_Plane_016_mesh_layer_5_tri_0[];
extern Gfx mat_sl_dl_evil_lair_floor[];
extern Gfx mat_revert_sl_dl_evil_lair_floor[];
extern Gfx sl_dl_Plane_016_mesh_layer_5[];
extern Gfx sl_dl_material_revert_render_settings[];
