extern const GeoLayout wmotr_area_1_geo[];
extern const GeoLayout wmotr_area_1[];
extern const Collision wmotr_area_1_collision[];
extern const MacroObject wmotr_area_1_macro_objs[];
extern Lights1 wmotr_dl_nice_lights;
extern Lights1 wmotr_dl_rock_lights;
extern u8 wmotr_dl__0E00F010_rgba16[];
extern u8 wmotr_dl_AdvGgtDimInd01_ia8[];
extern u8 wmotr_dl_gen_i8[];
extern u8 wmotr_dl_BORDER_1_ci4[];
extern u8 wmotr_dl_BORDER_1_ci4_pal_rgba16[];
extern u8 wmotr_dl_auto_ci8[];
extern u8 wmotr_dl_auto_ci8_pal_rgba16[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_0[46];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_1[89];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wmotr_dl_Cube_mesh_layer_1_vtx_2[115];
extern Gfx wmotr_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx wmotr_dl_Cube_001_mesh_layer_1_vtx_0[414];
extern Gfx wmotr_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Text_012_mesh_layer_1_vtx_0[1006];
extern Gfx wmotr_dl_Text_012_mesh_layer_1_tri_0[];
extern Vtx wmotr_dl_Text_013_mesh_layer_1_vtx_0[985];
extern Gfx wmotr_dl_Text_013_mesh_layer_1_tri_0[];
extern Gfx mat_wmotr_dl_rock2_layer1[];
extern Gfx mat_revert_wmotr_dl_rock2_layer1[];
extern Gfx mat_wmotr_dl_grassy_layer1[];
extern Gfx mat_revert_wmotr_dl_grassy_layer1[];
extern Gfx mat_wmotr_dl_nice[];
extern Gfx mat_revert_wmotr_dl_nice[];
extern Gfx mat_wmotr_dl_rock[];
extern Gfx mat_wmotr_dl_text_rainbow_001[];
extern Gfx mat_revert_wmotr_dl_text_rainbow_001[];
extern Gfx wmotr_dl_Cube_mesh_layer_1[];
extern Gfx wmotr_dl_Cube_001_mesh_layer_1[];
extern Gfx wmotr_dl_Text_012_mesh_layer_1[];
extern Gfx wmotr_dl_Text_013_mesh_layer_1[];
extern Gfx wmotr_dl_material_revert_render_settings[];
