COURSE_ACTS(COURSE_BOB, _("   SKYSCRAPER CITY"), 	_("ELECTRIC PLATFORMING"), 	_("PENTAGONAL TOWER"), 	_("SPEED TRICKERY"), 	_("SLIPPERY ROOFS"), 	_("5 LIT WINDOWS"), 	_("INSIDE THE CAGE"))

COURSE_ACTS(COURSE_WF, _("   FLOATING LAVA LAND"), 	_("UP THE LAVAFALLS"), 	_("A STRANGE CONSTRUCTION"), 	_("SLIDE AND BOUNCE"), 	_("VICTORIOUS METAL MARIO"), 	_("WALLKICKS OVER LAVA"), 	_("SHELL RIDE FOR SECRETS"))

COURSE_ACTS(COURSE_JRB, _("   MYSTERIOUS FLYING CASTLE"), 	_("THE LONELY TOWER"), 	_("IMPRISONED STAR"), 	_("ROOF CLIMBING"), 	_("PARKOUR IN THE CORRIDORS"), 	_("BLJ ROOFS"), 	_("MAGICAL FLYING GOOMBAS"))

COURSE_ACTS(COURSE_CCM, _("   DEVASTATED FOREST"), 	_("GLITCHY CLIMBING"), 	_("CRAZY WALLKICKS"), 	_("THE TREE'S CAGE"), 	_("TRAVERSING THE GRILLS"), 	_("LADDER CLIMBING TO THE TOP"), 	_("EXTREME CHAIN PLATFORMING"))

COURSE_ACTS(COURSE_BBH, _("   ETERNAL WINTER"), 	_("INTRIGUING FLOATING TREES"), 	_("AROUND THE OUTER WALL"), 	_("PERILOUS BOX JUMPING"), 	_("INSIDE THE IGLOO"), 	_("SLOPES IN THE CAVE"), 	_("CORRUPTED CAVERN"))

COURSE_ACTS(COURSE_HMC, _("   GLITCH FACTORY"), 	_("CHUCKYA CLIP"), 	_("METAL CAP EXPERIMENT"), 	_("CHUCKYA BOUNCE"), 	_("CHUCKYA WARP"), 	_("PUZZLING SLOPES"), 	_("HYPER KOOPA GENE EXTRACTION"))

COURSE_ACTS(COURSE_LLL, _("   UNDERWATER REALM"), 	_("ECCENTRIC ZIGZAGS"), 	_("SLIPPERY WOODEN RUINS"), 	_("GOOMBA CARNAGE"), 	_("LONELY SAND TOWER"), 	_("THROUGH THE QUICKSAND FIELD"), 	_("SAND CASTLE EXPLORATION"))

COURSE_ACTS(COURSE_SSL, _("   MOON STATION"), 	_("EXPERIMENTAL SCAFFOLDING"), 	_("ARMS WORKOUT"), 	_("CHUCKYA TIME TRIAL"), 	_("SLOPE FANTASY"), 	_("SHARPENED ROCKS"), 	_("SPEEDKICK INVESTIGATION"))

COURSE_ACTS(COURSE_DDD, _("   SHROOM SWAMP"), 	_("INVADED ROTTEN TREE"), 	_("OVERGROWN SHROOM TERRITORY"), 	_("MINI MUSHROOM PRECISION"), 	_("CRAZY LEAPS ACROSS THE SWAMP"), 	_("UNSTABLE SWITCHES"), 	_("TREE TRUNK ASCENT"))

COURSE_ACTS(COURSE_SL, _("   FORSAKEN PRISON"), 	_("DEMANDING ROOF CLIMB"), 	_("ALTERNATE ROOF ESCAPE"), 	_("FINAL PRISONER"), 	_("PROTECTED BASEMENT"), 	_("STAR FRAGMENT ASCENSION"), 	_("SLIDEKICK SHOWOFF"))

COURSE_ACTS(COURSE_WDW, _(""), 	_("SHOCKING ARROW LIFTS!"), 	_("TOP O' THE TOWN"), 	_("SECRETS IN THE SHALLOWS & SKY"), 	_("EXPRESS ELEVATOR--HURRY UP!"), 	_("GO TO TOWN FOR RED COINS"), 	_("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _(""), 	_("SCALE THE MOUNTAIN"), 	_("MYSTERY OF THE MONKEY CAGE"), 	_("SCARY 'SHROOMS, RED COINS"), 	_("MYSTERIOUS MOUNTAINSIDE"), 	_("BREATHTAKING VIEW FROM BRIDGE"), 	_("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _(""), 	_("PLUCK THE PIRANHA FLOWER"), 	_("THE TIP TOP OF THE HUGE ISLAND"), 	_("REMATCH WITH KOOPA THE QUICK"), 	_("FIVE ITTY BITTY SECRETS"), 	_("WIGGLER'S RED COINS"), 	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _(""), 	_("ROLL INTO THE CAGE"), 	_("THE PIT AND THE PENDULUMS"), 	_("GET A HAND"), 	_("STOMP ON THE THWOMP"), 	_("TIMED JUMPS ON MOVING BARS"), 	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _(""), 	_("CRUISER CROSSING THE RAINBOW"), 	_("THE BIG HOUSE IN THE SKY"), 	_("COINS AMASSED IN A MAZE"), 	_("SWINGIN' IN THE BREEZE"), 	_("TRICKY TRIANGLES!"), 	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   FINAL DELIRIUM"))
SECRET_STAR(16, _("   BOWSER IN THE FIRE SEA"))
SECRET_STAR(17, _("   BOWSER IN THE SKY"))
SECRET_STAR(18, _("   MUSHROOM KINGDOM"))
SECRET_STAR(19, _("   MAGMATIC HELL"))
SECRET_STAR(20, _("   CLOUD HEAVEN"))
SECRET_STAR(21, _(""))
SECRET_STAR(22, _("   MUSHROOM KINGDOM"))
SECRET_STAR(23, _("   BLOCKY MESS"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   OTHER STARS"))
EXTRA_TEXT(0,_("A SIDE COURSE STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
