#include "src/game/envfx_snow.h"

const GeoLayout castle_courtyard_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, 0, 8, 0, 90, 0, 0, castle_courtyard_dl_b_clouds_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, 0, -1272, 0, 90, 0, 0, castle_courtyard_dl_d_blind_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, 74, -1272, -291, 90, 0, -90, castle_courtyard_dl_d_blind_001_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, -214, -1272, -361, 90, 0, 180, castle_courtyard_dl_d_blind_002_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, -288, -1272, -74, 90, 0, 90, castle_courtyard_dl_d_blind_003_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_FORCE, -107, -1535, -181, 90, 0, 0, castle_courtyard_dl_d_stone_mesh_layer_0),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -107, -1535, -181, 90, 0, 0, castle_courtyard_dl_e_atrium_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 8, 0),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3472, -244, 559, castle_courtyard_dl_pillar_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1992, -244, -668, castle_courtyard_dl_pillar_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -1992, -244, 259, castle_courtyard_dl_pillar_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3472, -244, -968, castle_courtyard_dl_pillar_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -3502, 37, -134, castle_courtyard_dl_s_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 74, -1272, -291, 90, 0, -90, castle_courtyard_dl_s_fire_entrance_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -214, -1272, -361, 90, 0, 180, castle_courtyard_dl_s_ice_entrance_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 0, -1272, 0, 90, 0, 0, castle_courtyard_dl_sand_entrance_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -288, -1272, -74, 90, 0, 90, castle_courtyard_dl_sand_entrance_003_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_courtyard_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_ABOVE_CLOUDS, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(16, 0, -8, 0, 0, -108, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_courtyard_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, castle_courtyard_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, castle_courtyard_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
