extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_evil_lair_floor_lights;
extern u8 castle_inside_dl_cs_brokentile04_alb_ci8[];
extern u8 castle_inside_dl_cs_brokentile04_alb_ci8_pal_rgba16[];
extern Vtx castle_inside_dl_Plane_008_mesh_layer_5_vtx_0[37];
extern Gfx castle_inside_dl_Plane_008_mesh_layer_5_tri_0[];
extern Gfx mat_castle_inside_dl_evil_lair_floor[];
extern Gfx mat_revert_castle_inside_dl_evil_lair_floor[];
extern Gfx castle_inside_dl_Plane_008_mesh_layer_5[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
